#!/bin/bash

#dtoverlay dwc2
#modprobe dwc2
modprobe libcomposite

cd /sys/kernel/config/usb_gadget/
mkdir -p gadget
cd gadget
echo 0x1d6b > idVendor # Linux Foundation
echo 0x0104 > idProduct # Multifunction Composite Gadget
echo 0x0100 > bcdDevice # v1.0.0
echo 0x0200 > bcdUSB # USB2
echo 0xEF > bDeviceClass
echo 0x02 > bDeviceSubClass
echo 0x01 > bDeviceProtocol


mkdir -p strings/0x409
echo "fedcba9876543210" > strings/0x409/serialnumber
echo "by vlad" > strings/0x409/manufacturer
echo "HID & MASS" > strings/0x409/product
mkdir -p configs/c.1/strings/0x409
echo "Config 1:" > configs/c.1/strings/0x409/configuration
echo 250 > configs/c.1/MaxPower



 OS descriptors
echo 1       > os_desc/use
echo 0xcd    > os_desc/b_vendor_code
echo MSFT100 > os_desc/qw_sign
#echo RNDIS   > functions/rndis.usb0/os_desc/interface.rndis/compatible_id
#echo 5162001 > functions/rndis.usb0/os_desc/interface.rndis/sub_compatible_id

#ln -s configs/c.1 os_desc
#mkdir -p functions/rndis.usb0
#ln -s functions/rndis.usb0 configs/c.1/

# Add functions here
#mkdir -p functions/acm.usb0
#ln -s functions/acm.usb0 configs/c.1/



FILE=/home/pi/usbfs/usbdisk.img
#mkdir -p ${FILE/img/d}
#mount -o loop,ro, -t vfat $FILE ${FILE/img/d} # FOR IMAGE CREATED WITH DD
mkdir -p functions/mass_storage.usb0
echo 1 > functions/mass_storage.usb0/stall
echo 0 > functions/mass_storage.usb0/lun.0/cdrom
echo 0 > functions/mass_storage.usb0/lun.0/ro
echo 0 > functions/mass_storage.usb0/lun.0/nofua
echo $FILE > functions/mass_storage.usb0/lun.0/file
ln -s functions/mass_storage.usb0 configs/c.1/


mkdir -p functions/hid.0
echo 1 > functions/hid.0/protocol #Keyboard
echo 1 > functions/hid.0/subclass #Boot Interface Subclass
echo 8 > functions/hid.0/report_length
echo -ne \\x05\\x01\\x09\\x06\\xA1\\x01\\x05\\x07\\x19\\xE0\\x29`
	`\\xE7\\x15\\x00\\x25\\x01\\x75\\x01\\x95\\x08\\x81\\x02`
	`\\x95\\x01\\x75\\x08\\x81\\x01\\x95\\x05\\x75\\x01\\x05`
	`\\x08\\x19\\x01\\x29\\x05\\x91\\x02\\x95\\x01\\x75\\x03`
	`\\x91\\x01\\x95\\x06\\x75\\x08\\x15\\x00\\x25\\x65\\x05`
	`\\x07\\x19\\x00\\x29\\x65\\x81\\x00\\xC0 > functions/hid.0/report_desc
ln -s functions/hid.0 configs/c.1/


mkdir -p functions/hid.1
echo 2 > functions/hid.1/protocol #Mouse
echo 1 > functions/hid.1/subclass #Boot Interface Subclass
echo 8 > functions/hid.1/report_length
echo -ne \\x05\\x01\\x09\\x02\\xA1\\x01\\x09\\x01\\xA1\\x00\\x05`
	`\\x09\\x19\\x01\\x29\\x03\\x15\\x00\\x25\\x01\\x95\\x03`
	`\\x75\\x01\\x81\\x02\\x95\\x01\\x75\\x05\\x81\\x01\\x05`
	`\\x01\\x09\\x30\\x09\\x31\\x15\\x81\\x25\\x7F\\x75\\x08`
	`\\x95\\x02\\x81\\x06\\xC0\\xC0 > functions/hid.1/report_desc
ln -s functions/hid.1 configs/c.1/


# see gadget configurations below
# End functions

#udevadm settle -t 5 || :
ls /sys/class/udc > UDC
#ifconfig usb0 10.0.0.2 netmask 255.255.255.252 up
#route add -net default gw 10.0.0.1
sleep 5&&chmod 666 /dev/hidg0 /dev/hidg1 functions/mass_storage.usb0/lun.0/file
